import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
    # "~/.config/alacritty/themes/themes/challenger_deep.toml"
]

[font]
size = 11.0

[font.normal]
family = "Jetbrains Mono Nerd Font"
# family = "VictorMono NF SemiBold"
style = "Regular"

[window]
# opacity = 0.9

[window.padding]
x = 10
y = 15
